version: '3.9'
services:

  app:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    working_dir: /var/www/html/
    restart: unless-stopped
    # command: sh -c "cp .env.example .env && php artisan key:generate && php artisan migrate --seed && php artisan storage:link" // TODO: To be automated.
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ecommerce
      DB_USERNAME: user
      DB_PASSWORD: user_password
    depends_on:
      - mysql
    networks:
      app-network:
 
  webserver:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
      - ./Docker/Nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      app-network:
 
 
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    networks:
      app-network:

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
      ports:
        - 8001:80
      networks:
        app-network:
      depends_on:
        - mysql
 
#Docker Networks
networks:
  app-network:
    driver: bridge